name: Create Issue on PR to Main

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create an issue labeled "Done"
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;
            const prUser = context.payload.pull_request.user.login;

            const issueTitle = `PR #${prNumber} Merged to Main: ${prTitle}`;
            const issueBody = `Pull request by @${prUser} was opened and targets the main branch.\n\nPR Link: ${context.payload.pull_request.html_url}`;

            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['Done']
            });

            console.log(`Created issue #${issue.data.number} with 'Done' label.`);
